In [3]:

import pandas as pd

result = pd.read_pickle('./metrics_summary.pkl').set_index('set')


result_cm1 = result.loc['kc1'].drop(columns=['mean_pool', 'std_pool'])
result_cm1.round(3).transpose()

set             kc1    kc1    kc1
hardness       None   Hard   Easy
strategy      GASEN  GASEN  GASEN
mean_auc_roc  0.589  0.537  0.562
std_auc_roc   0.069  0.056  0.059
mean_acc      0.841  0.842  0.848
std_acc       0.023  0.023  0.008
mean_f1       0.588  0.512  0.558
std_f1        0.076  0.077  0.081
mean_g1       0.631  0.534  0.588
std_g1        0.073  0.094   0.09
mean_2xfault   0.12  0.327  0.063
std_2xfault   0.007  0.014  0.005
mean_disagr   0.303  0.381  0.273
std_disagr    0.022  0.016  0.012

In [4]:
#result.to_csv("Resultado", sep='\t', encoding='utf-8')
result_cm1 = result.loc['cm1'].drop(columns=['mean_pool', 'std_pool'])
result_cm1.round(3).transpose()

set             cm1    cm1    cm1
hardness       None   Hard   Easy
strategy      GASEN  GASEN  GASEN
mean_auc_roc  0.499  0.499  0.499
std_auc_roc   0.003  0.003  0.003
mean_acc        0.9    0.9    0.9
std_acc       0.008  0.008  0.008
mean_f1       0.474  0.474  0.474
std_f1        0.002  0.002  0.002
mean_g1       0.474  0.474  0.474
std_g1        0.002  0.002  0.002
mean_2xfault  0.105  0.493  0.052
std_2xfault   0.005   0.07  0.019
mean_disagr   0.351  0.353   0.35
std_disagr    0.026  0.062  0.047